
/*
	connectionstring - root:11111111@tcp(127.0.0.1:3306)/dev
    id - root
    pwd - 11111111
*/

CREATE DATABASE `dev` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `TBL_ADDITIONAL_USER` (
  `USER_KEY` varchar(50) NOT NULL COMMENT '유저 고유키',
  `USER_TYPE` varchar(20) NOT NULL COMMENT 'UserId 고객아이디, Hp 휴대폰, Email 이메일, Nickname 별명',
  `TYPE_VALUE` varchar(255) DEFAULT NULL COMMENT '해당값',
  PRIMARY KEY (`USER_KEY`,`USER_TYPE`),
  KEY `USER_TYPE_VALUE_INDEX` (`USER_TYPE`,`TYPE_VALUE`),
  KEY `TYPE_VALUE_INDEX` (`TYPE_VALUE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TBL_SCTRAN` (
  `TRAN_KEY` varchar(50) NOT NULL COMMENT '문자발송키',
  `HP` varchar(256) NOT NULL COMMENT '휴대폰번호',
  `NUM` varchar(6) NOT NULL COMMENT '인증번호',
  `EXPIRE_DATE` datetime NOT NULL COMMENT '만료일',
  `CERT_COMP_DATE` datetime DEFAULT NULL COMMENT '인증만료일',
  PRIMARY KEY (`TRAN_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TBL_TOKEN` (
  `USER_KEY` varchar(50) NOT NULL COMMENT '유저 고유키',
  `TOKEN` varchar(500) DEFAULT NULL COMMENT '유저토큰',
  `EXPIRE_DATE` datetime DEFAULT NULL COMMENT '만료일',
  PRIMARY KEY (`USER_KEY`),
  KEY `TBL_TOKEN_TOKEN_INDEX` (`TOKEN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TBL_USER` (
  `USER_KEY` varchar(50) NOT NULL COMMENT '유저 고유키',
  `REG_DATE` datetime DEFAULT NULL COMMENT '등록일',
  `USER_NAME` varchar(255) NOT NULL COMMENT '고객이름',
  `PWD` varchar(256) NOT NULL COMMENT '비밀번호',
  PRIMARY KEY (`USER_KEY`),
  UNIQUE KEY `USER_KEY_UNIQUE` (`USER_KEY`),
  KEY `USER_KEY_PWD_INDEX` (`USER_KEY`,`PWD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
